group:
  - files:
      - source: .github/
        dest: .github/
        deleteOrphaned: true
        exclude: |
           sync.yml
           workflows/sync-files.yml
    repos: |
      prom-client-net/prom-client
      prom-client-net/prom-client-dependencyinjection
      prom-client-net/prom-client-healthchecks
      prom-client-net/prom-client-httprequestdurations
      prom-client-net/prom-client-aspnetcore
      prom-client-net/prom-client-metricpusher
      prom-client-net/prom-client-metricserver
