name: CI

on:
  push:
    branches:
      - 'master'
    tags:
      - '!refs/tags/*'

jobs:
  build-publish-dev:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/prometheusclientnet/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GH_DEPLOY_KEY}}
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Tests
        run: dotnet test --no-build -c Release
      - name: Pack artifacts
        run: dotnet pack src/* --no-build -c Release --version-suffix dev-$(date +%s) -o artifacts/
      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nupkg
          path: artifacts/*
      - name: Publish to GitHub
        run: dotnet nuget push "artifacts/*.nupkg" --skip-duplicate --no-symbols true
