name: Sync Files

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-files:
    name: Sync Files
    if: github.repository == 'prom-client-net/prom-client-tmpl'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Synchronization
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_FULL_PAT }}
          CONFIG_PATH: .github/sync-config.yml
          COMMIT_PREFIX: "sync:"
          BRANCH_PREFIX: "sync/SOURCE_REPO_NAME"
          ORIGINAL_MESSAGE: true
          COMMIT_EACH_FILE: false
          GIT_USERNAME: phnx47[bot]
          GIT_EMAIL: 78849906+phnx47-bot@users.noreply.github.com
